all: p1 p2 p3 p4

p1:p1.cpp
	g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 p1.cpp -lm -o p1
p2:p2.cpp
	g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 p2.cpp -lm -o p2
p3:p3.cpp
	g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 p3.cpp -lm -o p3
p4:p4.cpp
	g++ -DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 p4.cpp -lm -o p4

